### PR TITLE
docs: highlight callouts

### PR DESCRIPTION
**Pull request by twlite**
This adds GFM callout to improve readability of the documentation.

| Before | After |
|--------|-------|
| image | image |
| image | image |

### CODE REVIEW

**Comment by twlite** [comment]
I'm marking this as a draft for now as I'm going to look for more improvements.

**Comment by souzatharsis** [comment]
Nice!

**Comment by twlite** [comment]
This is ready for review. I have fixed callouts and codeblock issue as well.

**Review by souzatharsis — APPROVED** [review]

**Comment by souzatharsis** [comment]
Merged. Thanks for your contribution.

**Pull request merged**
