### PR TITLE
update pypdf with pymupdf(10x faster then pypdf)

### PR DESCRIPTION
**Pull request by Devparihar5**
**Commit Message:**

Optimized PDF parsing performance by switching to PyMuPDF

- Compared PDF extraction performance between PyMuPDF and PyPDF using the same document (`data/pdf/s41598-024-58826-w.pdf` - 14 pages).
- Results: 
   - **PyMuPDF** took 0.047 seconds.
   - **PyPDF** took 0.493 seconds.
- Significant improvement in processing time achieved using PyMuPDF, enhancing overall efficiency for PDF handling in the project.

### CODE REVIEW

**Comment by souzatharsis** [comment]
Thanks! That's an impressive gain in performance for this use case.

You should also update the pyproject.toml file updating this dependency.

We will add a contributors guide soon to clarify those steps.

Thanks!

**Comment by Devparihar5** [comment]
> Thanks! That's an impressive gain in performance for this use case.
> 
> You should also update the pyproject.toml file updating this dependency.
> 
> We will add a contributors guide soon to clarify those steps.
> 
> Thanks!

it's done, you can check now

**Review by souzatharsis — APPROVED** [review]
LGTM

**Review by souzatharsis — COMMENTED** [review]
LGTM

**Review by souzatharsis — COMMENTED** [review]
LGTM

**Comment by souzatharsis** [comment]
@Devparihar5 this LGTM

I merged it and for some reason only the toml file was updated.

Could you please submit PR again? Apologies for the confusion thanks for your contribution.

**Pull request merged**
